name: hal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  curved_navigation_bar: ^1.0.6
  firebase_dynamic_links: ^6.1.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  lottie: ^3.3.1
  meta: ^1.16.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
