// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh9xIqEFccJWh0VpSv-ZchCIGb2kGZ-mg',
    appId: '1:1028098768662:web:66f1d026715938872b5a37',
    messagingSenderId: '1028098768662',
    projectId: 'hal-app-32853',
    authDomain: 'hal-app-32853.firebaseapp.com',
    storageBucket: 'hal-app-32853.firebasestorage.app',
    measurementId: 'G-0863L4Y44J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6vfIFMOmkT75YTetVsOi3KIWQLHL_aQ',
    appId: '1:1028098768662:android:074ee9fc3b243c0a2b5a37',
    messagingSenderId: '1028098768662',
    projectId: 'hal-app-32853',
    storageBucket: 'hal-app-32853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FZ68xup7Ry_XPkluU1KPQerJYw1ZeEM',
    appId: '1:1028098768662:ios:533e9dc444c69e172b5a37',
    messagingSenderId: '1028098768662',
    projectId: 'hal-app-32853',
    storageBucket: 'hal-app-32853.firebasestorage.app',
    iosBundleId: 'com.example.halApp',
  );
}
